export const LETTER_BOX_MAX_VIEW_WIDTH_AS_PX_UNIT_NUMBER = 500;
export const LETTER_BOX_MAX_VIEW_WIDTH_AS_STRING = `${LETTER_BOX_MAX_VIEW_WIDTH_AS_PX_UNIT_NUMBER}px`;

export const TOTAL_QUESTION = 10;
